# Policy Iteration Algorithm

Policy Iteration is a method used to solve Markov Decision Processes (MDPs). It alternates between two steps: policy evaluation and policy improvement, iteratively improving the policy until it converges to the optimal policy.

### Steps of the Policy Iteration Algorithm:

1. **Initialization**:
    - Start with an arbitrary policy $\pi$.
    - Initialize the value function $V(s)$ for all states $s$.

2. **Policy Evaluation**:
    - Compute the value function $V^\pi(s) $ for the current policy $\pi$ by solving the Bellman equation:  
        $$  
        V^\pi(s) = \sum_{s'} P(s'|s, \pi(s)) \left[ R(s, \pi(s), s') + \gamma V^\pi(s') \right]  
        $$  
        where:  
        - $P(s'|s, a)$: Transition probability.  
        - $R(s, a, s')$: Reward for transitioning from state \( s \) to \( s' \) using action \( a \).  
        - $\gamma$: Discount factor. 
    - Update the policy by acting greedily with respect to the value function:
      $$
      \pi'(s) = \arg\max_a \sum_{s'} P(s'|s, a) \left[ R(s, a, s') + \gamma V^\pi(s') \right]
      $$

4. **Convergence**:
    - Repeat the policy evaluation and policy improvement steps until the policy no longer changes (i.e., it converges to the optimal policy $\pi^*$).

Policy Iteration is guaranteed to converge to the optimal policy in a finite number of iterations for finite MDPs.


In [50]:
def policy_evaluation(env, policy, v, gamma=1.0):
    """
    Evaluate the value function for a given policy.

    Parameters:
    - env: The environment object (e.g., OpenAI Gym environment) that provides the transition dynamics.
    - policy: A numpy array representing the current policy, where policy[state] gives the action to take in that state.
    - v: A numpy array representing the current value function, where v[state] is the value of the state.
    - gamma: The discount factor (default is 1.0), which determines the importance of future rewards.

    Returns:
    - v: The updated value function after policy evaluation.
    """
    
    # Create a copy of the current value function to track updates
    v_ = np.copy(v)
    
    # Iterate over all states in the environment
    for state in range(env.observation_space.n):
        # Get the action dictated by the current policy for this state
        policy_action = policy[state]
        
        # Update the value of the current state using the Bellman equation
        # Sum over all possible transitions (probability, next state, reward, done)
        v[state] = sum([
            prob * (reward + gamma * v_[state_]) 
            for prob, state_, reward, _ in env.env.P[state][policy_action]
        ])
        
    # Return the final value function
    return v



def policy_improvement(env, v, gamma=1.0):
    # Initialize a new policy with zeros for all states
    policy = np.zeros(env.observation_space.n)
    
    # Iterate over all states in the environment
    for state in range(env.observation_space.n):
        # Initialize an array to store the action-value function (Q-values) for all actions
        q = np.zeros(env.action_space.n)
        
        # Iterate over all possible actions for the current state
        for action in range(env.action_space.n):
            # Compute the Q-value for the current action by summing over all possible transitions
            # (probability, next state, reward, done)
            q[action] = sum([
                prob * (reward + gamma * v[state_]) 
                for prob, state_, reward, _ in env.env.P[state][action]
            ])
        
        # Select the action that maximizes the Q-value and update the policy for the current state
        policy[state] = np.argmax(q)
    
    # Return the improved policy
    return policy

In [51]:
def policy_iteration(env, gamma=1.0):
    """ Policy-Iteration algorithm """

    # Initialize the value function for all states to 0
    v = np.zeros(env.observation_space.n)

    # Initialize policy randomly. 
    policy = np.random.choice(env.action_space.n, size=(env.observation_space.n))
    max_iterations = 20000
    gamma = 1.0
    for i in range(max_iterations):
        new_v = policy_evaluation(env, policy, v, gamma)
        new_policy = policy_improvement(env, new_v, gamma)
        #print(new_policy.reshape(8,8))
        # if (np.all(policy == new_policy)):
            # print('Policy-Iteration converged at step %d.' % (i + 1))


            # print(new_v.reshape(8,8))
         
        policy = np.copy(new_policy)
        v_ = np.copy(new_v)
    return policy






# Testing the Policy Iteration Algorithm on FrozenLake Environment

The FrozenLake environment is a classic reinforcement learning problem where the agent must navigate a grid world to reach the goal while avoiding holes. The environment is stochastic, meaning the agent's actions may not always lead to the intended outcome.

### Environment Details:
- **Environment Name**: `FrozenLake8x8-v1`
- **Grid Size**: 8x8
- **Objective**: Navigate from the starting point to the goal while avoiding holes.
- **Actions**: Discrete actions represented by numbers:
    - `0`: Left
    - `1`: Down
    - `2`: Right
    - `3`: Up
- **Rewards**: A reward of 1 is given for reaching the goal; otherwise, the reward is 0.

### Testing Workflow:
1. **Policy Iteration**:
    - Use the Policy Iteration algorithm to compute the optimal policy for the FrozenLake environment.
    - The algorithm alternates between policy evaluation and policy improvement until convergence.

2. **Evaluation**:
    - Evaluate the optimal policy by running multiple episodes and calculating the average score.

3. **Visualization**:
    - Test the optimal policy by running a single episode and rendering the environment to visualize the agent's behavior.

### Results:
- **Optimal Policy**: The computed policy is stored in the variable `optimal_policy`.
- **Average Score**: The average score over multiple episodes is stored in the variable `score`.

In [52]:
def run_episode(env, policy, gamma = 1.0, render = False):
    """
    Runs a single episode using the given policy.

    Parameters:
    - env: The environment object (e.g., OpenAI Gym environment).
    - policy: A numpy array representing the policy, where policy[state] gives the action to take in that state.
    - gamma: The discount factor (default is 1.0), which determines the importance of future rewards.
    - render: A boolean flag to render the environment during the episode (default is False).

    Returns:
    - total_reward: The total discounted reward obtained during the episode.
    """
    observation = env.reset()  # Reset the environment to the initial state.
    total_reward = 0  # Initialize the total reward.
    step_idx = 0  # Initialize the step counter.

    if isinstance(observation, tuple):
        observation = observation[0]  # Extract the initial state from the reset output.
    else:
        observation = observation

    while True:
        if render:
            env.render()  # Render the environment if the render flag is True.

        action = int(policy[observation])  # Select the action based on the policy.
        try:
            # Take the action and observe the next state, reward, and done flag.
            observation, reward, done, truncated, _ = env.step(action)
            # Accumulate the discounted reward.
            total_reward += (gamma ** step_idx * reward)
            step_idx += 1  # Increment the step counter.
        except Exception as e:
            # Handle any exceptions that occur during the episode.
            print(f"An error occurred during the episode: {e}")
            break
        if done:  # Exit the loop if the episode is done.
            break

    return total_reward  # Return the total discounted reward.



def evaluate_policy(env, policy, gamma = 1.0, n = 100):
    """
    Evaluates the given policy by running multiple episodes and averaging the total rewards.

    Parameters:
    - env: The environment object (e.g., OpenAI Gym environment).
    - policy: A numpy array representing the policy, where policy[state] gives the action to take in that state.
    - gamma: The discount factor (default is 1.0), which determines the importance of future rewards.
    - n: The number of episodes to run for evaluation (default is 100).

    Returns:
    - The average total discounted reward over n episodes.
    """
    scores = [run_episode(env, policy, gamma, False) for _ in range(n)]  # Run n episodes and collect scores.
    return np.mean(scores)  # Return the average score.

In [53]:
def test_episode(env, policy):
    """
    Runs a single episode to test the policy and renders the environment.

    Parameters:
    - env: The environment object (e.g., OpenAI Gym environment).
    - policy: A numpy array representing the policy, where policy[state] gives the action to take in that state.
    """
    observation = env.reset()  # Reset the environment to the initial state.
    if isinstance(observation, tuple):
        observation = observation[0]  # Extract the initial state from the reset output.
    else:
        observation = observation
        
    while True:
        env.render()  # Render the environment.
        # Take the action based on the policy and observe the next state and done flag.
        observation, _, done, truncated, _ = env.step(int(policy[observation]))
        if done:  # Exit the loop if the episode is done.
            break

In [54]:
import numpy as np
import gym


env_name  = 'FrozenLake8x8-v1' # 'FrozenLake-v0'
env = gym.make(env_name)
optimal_policy = policy_iteration(env, gamma = 1.0)
score = evaluate_policy(env, optimal_policy, gamma = 1.0)
print('Average scores = ', score)

Average scores =  1.0


In [55]:
# env = gym.make(env_name, render_mode='human')
# est_episode(env, optimal_policy)

In [56]:
print(optimal_policy.reshape(8, 8))

[[1. 2. 2. 1. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 2.]
 [0. 0. 0. 0. 2. 3. 3. 2.]
 [0. 0. 0. 1. 0. 0. 2. 2.]
 [0. 3. 0. 0. 2. 1. 3. 2.]
 [0. 0. 0. 1. 3. 0. 0. 2.]
 [0. 0. 1. 0. 0. 0. 0. 2.]
 [0. 1. 0. 0. 1. 2. 1. 0.]]


In [62]:
class GridWorldEnv(Env):
    def __init__(self, grid_size=4, holes=None, mode = None):
        super(GridWorldEnv, self).__init__()
        self.grid_size = grid_size
        self.holes = holes if holes else []  # List of hole states
        self.observation_space = spaces.Discrete(grid_size * grid_size)  # Total states
        self.action_space = spaces.Discrete(4)  # Actions: 0=Left, 1=Down, 2=Right, 3=Up

        self.mode = mode

        # Define the transition probabilities and rewards
        self.P = self._build_transition_probabilities()
        self.env = self  # Make the environment accessible via self.env

    def _build_transition_probabilities(self):
        P = {}
        for state in range(self.observation_space.n):
            P[state] = {action: [] for action in range(self.action_space.n)}
            x, y = divmod(state, self.grid_size)

            for action in range(self.action_space.n):
                if action == 0:  # Left
                    next_x, next_y = x, max(y - 1, 0)
                elif action == 1:  # Down
                    next_x, next_y = min(x + 1, self.grid_size - 1), y
                elif action == 2:  # Right
                    next_x, next_y = x, min(y + 1, self.grid_size - 1)
                elif action == 3:  # Up
                    next_x, next_y = max(x - 1, 0), y

                next_state = next_x * self.grid_size + next_y
                if next_state in self.holes:
                    reward = -1  # Negative reward for falling into a hole
                    done = True  # Episode ends if the agent falls into a hole
                elif next_state == self.observation_space.n - 1:
                    reward = 1  # Positive reward for reaching the goal
                    done = True
                else:
                    reward = 0  # No reward for other states
                    done = False

                P[state][action].append((1.0, next_state, reward, done))
        return P

    def reset(self):
        self.state = 0
        return self.state

    def step(self, action):
        transitions = self.P[self.state][action]
        prob, next_state, reward, done = transitions[0]
        self.state = next_state

        return next_state, reward, done, False, {}

    def render(self, mode='human'):
        grid = np.zeros((self.grid_size, self.grid_size), dtype=str)
        grid[:] = '.'
        for hole in self.holes:
            x, y = divmod(hole, self.grid_size)
            grid[x, y] = 'H'  # Mark holes
        x, y = divmod(self.state, self.grid_size)
        grid[x, y] = 'A'  # Mark agent's position
        grid[-1, -1] = 'G'  # Mark goal
        print("\n".join([" ".join(row) for row in grid]))
        print()

In [ ]:

env = GridWorldEnv(grid_size=4, holes=[5, 9, 13])
optimal_policy = policy_iteration(env, gamma = 1.0)
score = evaluate_policy(env, optimal_policy, gamma = 1.0)
print('Average scores = ', score)


In [65]:
optimal_policy.reshape(env.grid_size, env.grid_size)

array([[2., 2., 1., 1.],
       [1., 2., 1., 1.],
       [1., 2., 1., 1.],
       [2., 2., 2., 1.]])

In [66]:

env = GridWorldEnv(grid_size=4, holes=[5, 9, 13], mode='human')
test_episode(env, optimal_policy)
print(optimal_policy.reshape(env.grid_size, env.grid_size))


A . . .
. H . .
. H . .
. H . G

. A . .
. H . .
. H . .
. H . G

. . A .
. H . .
. H . .
. H . G

. . . .
. H A .
. H . .
. H . G

. . . .
. H . .
. H A .
. H . G

. . . .
. H . .
. H . .
. H A G

[[2. 2. 1. 1.]
 [1. 2. 1. 1.]
 [1. 2. 1. 1.]
 [2. 2. 2. 1.]]
